name: deploy to GatherBusData
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.csv'
      - '**.ipynb'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./result.zip . -i ./*.py
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: track_buses
          zip_file: result.zip
